### ISSUE TITLE
missing __init__.py

### ISSUE THREAD

**Issue by osresearch** [tiaanv/esphome-components#1]
with a recent checkout of esphome, this produces an compile time error:
```
src/main.cpp:34:1: error: 't547' does not name a type
 t547::T547 *t5_display;
 ^
``` 

It seems that without an empty `custom_components/t547/__init__.py`, esphome won't add the include headers to the `main.cpp`.  Touching that file is enough to make it work again: https://github.com/esphome/feature-requests/issues/1109#issuecomment-991136696

I'm not well-versed enough in esphome to know if there is something else that should be in that file, only that it worked for me...

**Comment by tiaanv** [comment]
You are 100% correct.  I actually have a `__init__.py` file in my source... for some reason it's not in GIT.
I'll add it..
EDIT:
After some investigation... Git skips uploading of empty files... go figure...  Added a single blank space to the file. Uploaded now.
