### ISSUE TITLE
Specify license?

### ISSUE THREAD

**Issue by nickolay** [tiaanv/esphome-components#4]
Hey,
I noticed you didn't specify the license for this repository.
Would you be willing to use the same license as [ESPHome does](https://github.com/esphome/esphome/blob/release/LICENSE) (MIT for Python / GPLv3 for C(++)?

To provide some context: I'm looking into making ESPHome work with the [ESP32-S3 based version of T5-4.7](https://www.lilygo.cc/products/t5-4-7-inch-e-paper-v2-3) by taking the same approach as you have (i.e. implementing esphome's display APIs using calls into lilygo's EPD library). I'm contemplating if I should make it a fork/variant of your component or a separate thing, inspired by your excellent work.

**Comment by tiaanv** [comment]
You may assume the licence is the same.  You are welcome to use this code in ANY way you like.

**Comment by nickolay** [comment]
Awesome, thank you! I'll ping you when I publish my code, in case you're curious.

**Comment by nickolay** [comment]
Here it is: https://github.com/nickolay/esphome-lilygo-t547plus

I would make a pull request to merge https://github.com/nickolay/esphome-lilygo-t547plus/commit/d5f96e39d606b1c4dc52045e24699ee7d29ee7ec and https://github.com/nickolay/esphome-lilygo-t547plus/commit/2b38b84023a4cfce6b203d6566893402811bb7af back to your repo, but I don't have the original T5 device to test them on.

**Comment by tiaanv** [comment]
I will test it.  Unfortunately, will only be during next week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
